# Generated by Django 5.2.17 on 2026-09-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('period_type', models.CharField(choices=[('fixed_date', 'Data fixa'), ('date_range', 'Faixa de datas'), ('next_months', 'Próximos N meses')], max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('months_ahead', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('drop_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='alerts.alert')),
            ],
            options={
                'verbose_name_plural': 'price histories',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.telegramuser'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(condition=models.Q(('target_price__isnull', False), ('drop_percentage__isnull', False), _connector='OR'), name='alert_has_target_price_or_drop_percentage'),
        ),
    ]
