# Generated by Django 5.2.17 on 2026-09-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_seed_check_prices_periodic_task'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alert',
            name='alert_has_target_price_or_drop_percentage',
        ),
        migrations.AddField(
            model_name='alert',
            name='flexible_weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alert',
            name='preferred_airlines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alert',
            name='require_checked_bag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='trip_duration_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='trip_type',
            field=models.CharField(choices=[('round_trip', 'Ida e volta'), ('one_way', 'Só ida')], default='round_trip', max_length=20),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='is_mistake_fare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='matched_departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='matched_destination',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='alert',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='alert',
            name='period_type',
            field=models.CharField(choices=[('fixed_date', 'Data fixa'), ('date_range', 'Faixa de datas'), ('next_months', 'Próximos N meses'), ('flexible_weekday', 'Dia da semana flexível')], max_length=20),
        ),
    ]
